export const colorOptions = [
    { key: 'red', text: 'Red', value: 'red' },
    { key: 'orange', text: 'Orange', value: 'orange' },
    { key: 'yellow', text: 'Yellow', value: 'yellow' },
    { key: 'olive', text: 'Olive', value: 'olive' },
    { key: 'green', text: 'Green', value: 'green' },
    { key: 'teal', text: 'Teal', value: 'teal' },
    { key: 'blue', text: 'Blue', value: 'blue' },
    { key: 'violet', text: 'Violet', value: 'violet' },
    { key: 'purple', text: 'Purple', value: 'purple' },
    { key: 'pink', text: 'Pink', value: 'pink' },
    { key: 'brown', text: 'Brown', value: 'brown' },
    { key: 'grey', text: 'Grey', value: 'grey' },
    { key: 'black', text: 'Black', value: 'black' },
  ]
